version: '3.4'
services:
  mongo:
    container_name: mongodb-shopping-cart
    image: mongo:3.6.8
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin321
      - MONGODB_DATABASE=shopping_cart_mrl
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    volumes:
      - ./docker/mongodb/:/docker-entrypoint-initdb.d
    networks:
      - marlon-network
  shopping-cart-api:
    image: shopping-cart-api
    restart: always
    environment:
      - MONGODB_USER=root
      - MONGODB_PASS=admin321
      - SPRING_PROFILES_ACTIVE=hom
    build: ./
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - marlon-network
networks:
    marlon-network:
        driver: bridge